-- Examples

DROP TABLE IF EXISTS MY_TABLE;
CREATE TABLE MY_TABLE (
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    RESUME VARCHAR(255) NOT NULL   
);

